
export const API_STATE = "state"
export const API_DURATION = "duration"
export const API_CATEGORY = "category"
export const API_OBJECT = "object"
export const API_SELECTION = "selection"
export const API_SUBCATEGORY = "subcategory"
export const API_IMAGE = "image"
export const API_BID = "bid"
export const API_MESSAGE = "message"
export const API_QUESTION = "questions"
export const API_QUESTION_AND_ANSWER = "question-and-answer"
export const API_ANSWER = "answer"
export const API_USER = 'user'
export const API_FOLLOWED_OBJECT = "followed-object"
export const API_FOLLOWED_OBJECT_BY_USER = "followed-object-by-user"
export const API_BIDDED_OBJECT_BY_USER = "bidded-object-by-user"
export const API_PURCHASED_OBJECT_BY_USER = "purchased-object-by-user"
export const API_TRANSACTION = "transaction"
export const API_OPERATION = "operation"
export const API_BALANCE = "account-balance"
export const API_OFFER_BANNER = "offer-banner"
export const API_DETAILLED_USER = "detailled-user"
export const API_DETAILLED_OBJECT = "detailled-object"

export const API_LOGIN = "rest-auth/login"
export const API_LOGOUT = "rest-auth/logout"
export const API_REGISTRATION = "rest-auth/registration"
