# Generated by Django 3.2.7 on 2021-09-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='path',
            field=models.CharField(default='ok', max_length=300),
            preserve_default=False,
        ),
    ]
