# Generated by Django 3.2.7 on 2021-12-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='parent',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='element',
            name='thumbnail_path',
            field=models.ImageField(max_length=1000, upload_to=''),
        ),
    ]
