# Generated by Django 3.2.7 on 2021-12-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0002_auto_20211213_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='parent',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='element',
            name='thumbnail_path',
            field=models.ImageField(upload_to=''),
        ),
    ]
