# Generated by Django 3.2.7 on 2021-09-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0003_hash_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash_image',
            name='image_hash',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hash_image',
            name='image_path',
            field=models.CharField(max_length=300),
        ),
    ]
