# Generated by Django 3.2.7 on 2021-09-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0004_auto_20210920_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
