# Generated by Django 3.2.7 on 2021-09-23 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0005_auto_20210921_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='image_hash',
        ),
        migrations.AlterField(
            model_name='element',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='element.hash_image'),
        ),
        migrations.AlterField(
            model_name='element',
            name='parent',
            field=models.CharField(default='UN', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Hash',
        ),
    ]
