# Generated by Django 3.2.7 on 2021-09-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0006_auto_20210923_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='element',
            name='parent',
            field=models.CharField(max_length=300),
        ),
    ]
